### ISSUE TITLE
Cannot integrate with other plugins mentioned in README

### ISSUE THREAD

**Issue by Blackening999** [arccoza/postcss-if-media#4]
This library is great but it isn't working with cutom-media nor with minmax:

```css
@custom-media --small-viewport (500px <= width <= 1700px);

h1 {
  ?if media --small-viewport {
    color: darkred;
  }
}

h1 {
  ?if media (500px <= width <= 1700px) {
    color: darkred;
  }
}
```
